baseURL = "https://www.dataday.life"
languageCode = "en-us"
title = "Data-Day Life"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
disqusShortname="https://datadaylife.disqus.com"